'use strict';

/**
 * Centralised configuration. Reads the environment once, coerces types, and
 * validates that the variables the dashboard cannot run without are present.
 * Importing this module is side-effect free; call assertValid() during startup
 * to fail fast with a readable message instead of a stack trace deep in a route.
 */

const config = Object.freeze({
  port: parseInt(process.env.PORT || '3001', 10),

  pterodactyl: Object.freeze({
    url: process.env.PTERO_URL,
    appKey: process.env.PTERO_APP_KEY,
    clientKey: process.env.PTERO_CLIENT_KEY,
    defaultUserId: parseInt(process.env.PTERO_DEFAULT_USER_ID || '1', 10),
  }),

  node: Object.freeze({
    publicIp: process.env.NODE_PUBLIC_IP,
  }),

  curseforgeApiKey: process.env.CURSEFORGE_API_KEY || '',

  jwtSecret: process.env.JWT_SECRET,

  statePollIntervalMs: parseInt(process.env.STATE_POLL_INTERVAL_SEC || '15', 10) * 1000,
});

const REQUIRED = [
  ['PTERO_URL', config.pterodactyl.url],
  ['PTERO_APP_KEY', config.pterodactyl.appKey],
  ['PTERO_CLIENT_KEY', config.pterodactyl.clientKey],
  ['NODE_PUBLIC_IP', config.node.publicIp],
  ['JWT_SECRET', config.jwtSecret],
];

/**
 * Throws if any required variable is missing. JWT_SECRET is generated by
 * `node setup.js`, so a missing one usually means setup hasn't been run.
 */
function assertValid() {
  const missing = REQUIRED.filter(([, value]) => !value).map(([name]) => name);
  if (missing.length) {
    throw new Error(
      `Missing required environment variable(s): ${missing.join(', ')}. ` +
      'Copy .env.example to .env and run `node setup.js <user> <password>`.'
    );
  }
}

module.exports = { config, assertValid };
